/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseproject;

import java.awt.Menu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ameer
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        c_name = new javax.swing.JTextField();
        c_phone = new javax.swing.JTextField();
        c_email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        c_addButton = new javax.swing.JButton();
        c_address = new javax.swing.JTextField();
        c_clrButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer");
        setBackground(new java.awt.Color(51, 255, 255));

        Container.setBackground(new java.awt.Color(102, 255, 255));

        l1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(204, 0, 204));
        l1.setText("Name");

        l2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(204, 0, 204));
        l2.setText("Address");

        l3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l3.setForeground(new java.awt.Color(204, 0, 204));
        l3.setText("Phone");

        l4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l4.setForeground(new java.awt.Color(204, 0, 204));
        l4.setText("Email");

        c_name.setBackground(new java.awt.Color(204, 204, 204));
        c_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_name.setForeground(new java.awt.Color(255, 0, 51));
        c_name.setToolTipText("Enter your name here");
        c_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nameActionPerformed(evt);
            }
        });
        c_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_nameKeyReleased(evt);
            }
        });

        c_phone.setBackground(new java.awt.Color(204, 204, 204));
        c_phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_phone.setForeground(new java.awt.Color(255, 0, 51));
        c_phone.setToolTipText("Enter your phone number here");

        c_email.setBackground(new java.awt.Color(204, 204, 204));
        c_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_email.setForeground(new java.awt.Color(255, 0, 51));
        c_email.setToolTipText("Enter your email here");
        c_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_emailActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 37, 27));
        jLabel1.setText("Customer");

        c_addButton.setBackground(new java.awt.Color(255, 255, 0));
        c_addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c_addButton.setForeground(new java.awt.Color(51, 0, 51));
        c_addButton.setText("Add");
        c_addButton.setToolTipText("");
        c_addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_addButtonActionPerformed(evt);
            }
        });

        c_address.setBackground(new java.awt.Color(204, 204, 204));
        c_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_address.setForeground(new java.awt.Color(255, 0, 0));
        c_address.setToolTipText("Enter your address here");
        c_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_addressActionPerformed(evt);
            }
        });
        c_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_addressKeyReleased(evt);
            }
        });

        c_clrButton.setBackground(new java.awt.Color(255, 255, 0));
        c_clrButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c_clrButton.setText("Clear");
        c_clrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_clrButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("H:\\CSE 3.1\\3.1\\LAB\\Data_Base LAB\\Warehouse_Management_System\\DatabaseProject\\src\\databaseproject\\rsz_customer2.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setRequestFocusEnabled(false);

        lbl_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_nameKeyReleased(evt);
            }
        });

        lbl_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_addressKeyReleased(evt);
            }
        });

        back_button.setBackground(new java.awt.Color(255, 255, 0));
        back_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l3)
                            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(l4)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(c_name, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(c_phone)
                            .addComponent(c_address)
                            .addComponent(c_email))
                        .addGap(98, 98, 98)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(c_addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c_clrButton, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(back_button, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                    .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1)))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l1)
                            .addComponent(c_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_addButton))
                        .addGap(12, 12, 12)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l3)
                                    .addComponent(c_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addComponent(l4))
                            .addComponent(c_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(c_clrButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(back_button)
                .addGap(240, 240, 240))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void c_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_emailActionPerformed

    private void c_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nameActionPerformed

    private void c_addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_addButtonActionPerformed
        // TODO add your handling code here:
        if(c_name.getText().trim().isEmpty() && c_address.getText().trim().isEmpty()){
            lbl_name.setText("Name is empty");
            lbl_address.setText("Address is empty");
        }
        else if(c_name.getText().trim().isEmpty()){
            lbl_name.setText("Name is empty");
        }
        else if(c_address.getText().trim().isEmpty()){
            lbl_address.setText("Address is empty");
        }
        else
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=WarehouseManagementSystem;user=sa;password=123467";
            Connection con = DriverManager.getConnection(url);
             String query = "insert into customer(name,customer_address,phone_no,email)values(?,?,?,?)";
             PreparedStatement pst = con.prepareStatement(query);
             pst.setString(1, c_name.getText());
             pst.setString(2, c_address.getText());
             pst.setString(3, c_phone.getText());
             pst.setString(4, c_email.getText());
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "Inserted Successfully!");
             
             
             
         }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_c_addButtonActionPerformed

    private void c_clrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_clrButtonActionPerformed
        // TODO add your handling code here:
             c_name.setText("");
             c_address.setText("");
             c_phone.setText("");
            c_email.setText("");
    }//GEN-LAST:event_c_clrButtonActionPerformed

    private void c_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_addressActionPerformed

    private void lbl_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_nameKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_lbl_nameKeyReleased

    private void lbl_addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_addressKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_lbl_addressKeyReleased

    private void c_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_nameKeyReleased
        // TODO add your handling code here:
        lbl_name.setText("");
    }//GEN-LAST:event_c_nameKeyReleased

    private void c_addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_addressKeyReleased
        // TODO add your handling code here:
        lbl_address.setText("");
    }//GEN-LAST:event_c_addressKeyReleased

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        Menu_Frame mf=new Menu_Frame();
       mf.setVisible(true);
       dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton back_button;
    private javax.swing.JButton c_addButton;
    private javax.swing.JTextField c_address;
    private javax.swing.JButton c_clrButton;
    private javax.swing.JTextField c_email;
    private javax.swing.JTextField c_name;
    private javax.swing.JTextField c_phone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_name;
    // End of variables declaration//GEN-END:variables
}
