/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseproject;

import java.awt.Color;
import java.awt.MenuBar;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JMenuBar;

/**
 *
 * @author DELL
 */
public class Menu_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Frame
     */
    public Menu_Frame() {
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        this.setSize(1000, 600);
        this.setLocationRelativeTo(null);
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuItem3 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar_Supplier = new javax.swing.JMenuBar();
        Supplier_Menu = new javax.swing.JMenu();
        supplier_add = new javax.swing.JMenuItem();
        supplier_view = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_Product_add = new javax.swing.JMenuItem();
        jMenuItem_Product_view = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_Transaction_In = new javax.swing.JMenuItem();
        jMenuItem_Transaction_out = new javax.swing.JMenuItem();
        jMenu_product_stock = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_CustomerAdd = new javax.swing.JMenuItem();
        jMenuItem_CustomerList = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem_StaffAdd = new javax.swing.JMenuItem();
        jMenuItem_staffLsit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem3.setText("jMenuItem3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("H:\\CSE 3.1\\3.1\\LAB\\Data_Base LAB\\Warehouse_Management_System\\Images\\WMS_back_4.png")); // NOI18N
        jLabel1.setText("                          ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jMenuBar_Supplier.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jMenuBar_Supplier, org.jdesktop.beansbinding.ELProperty.create("${background}"), jMenuBar_Supplier, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        Supplier_Menu.setBackground(new java.awt.Color(255,51,102));
        Supplier_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Supplier_Menu.setIcon(new javax.swing.ImageIcon("H:\\CSE 3.1\\3.1\\LAB\\Data_Base LAB\\Warehouse_Management_System\\Images\\clipart_60.png")); // NOI18N
        Supplier_Menu.setText("Supplier");
        Supplier_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supplier_MenuActionPerformed(evt);
            }
        });

        supplier_add.setText("ADD");
        supplier_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_addActionPerformed(evt);
            }
        });
        Supplier_Menu.add(supplier_add);

        supplier_view.setText("View");
        supplier_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_viewActionPerformed(evt);
            }
        });
        Supplier_Menu.add(supplier_view);

        jMenuBar_Supplier.add(Supplier_Menu);

        jMenu1.setIcon(new javax.swing.ImageIcon("H:\\CSE 3.1\\3.1\\LAB\\Data_Base LAB\\Warehouse_Management_System\\Images\\products_60.png")); // NOI18N
        jMenu1.setText("Product");

        jMenuItem_Product_add.setText("ADD");
        jMenuItem_Product_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Product_addActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Product_add);

        jMenuItem_Product_view.setText("View");
        jMenuItem_Product_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Product_viewActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Product_view);

        jMenuBar_Supplier.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("H:\\CSE 3.1\\3.1\\LAB\\Data_Base LAB\\Warehouse_Management_System\\Images\\pay_1.png")); // NOI18N
        jMenu2.setText("Transaction");

        jMenuItem_Transaction_In.setText("In");
        jMenuItem_Transaction_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Transaction_InActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Transaction_In);

        jMenuItem_Transaction_out.setText("Out");
        jMenu2.add(jMenuItem_Transaction_out);

        jMenuBar_Supplier.add(jMenu2);

        jMenu_product_stock.setText("Product Stock");
        jMenu_product_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_product_stockActionPerformed(evt);
            }
        });
        jMenuBar_Supplier.add(jMenu_product_stock);

        jMenu6.setIcon(new javax.swing.ImageIcon("H:\\CSE 3.1\\3.1\\LAB\\Data_Base LAB\\Warehouse_Management_System\\Images\\pay_60.png")); // NOI18N
        jMenu6.setText("OrderDetails");
        jMenuBar_Supplier.add(jMenu6);

        jMenu3.setIcon(new javax.swing.ImageIcon("H:\\CSE 3.1\\3.1\\LAB\\Data_Base LAB\\Warehouse_Management_System\\Images\\customer_60.png")); // NOI18N
        jMenu3.setText("Customer");

        jMenuItem_CustomerAdd.setText("ADD");
        jMenuItem_CustomerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CustomerAddActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_CustomerAdd);

        jMenuItem_CustomerList.setText("View");
        jMenuItem_CustomerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CustomerListActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_CustomerList);

        jMenuBar_Supplier.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon("H:\\CSE 3.1\\3.1\\LAB\\Data_Base LAB\\Warehouse_Management_System\\Images\\staff_60.png")); // NOI18N
        jMenu5.setText("Staff");

        jMenuItem_StaffAdd.setText("ADD");
        jMenuItem_StaffAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_StaffAddActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_StaffAdd);

        jMenuItem_staffLsit.setText("View");
        jMenuItem_staffLsit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_staffLsitActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_staffLsit);

        jMenuBar_Supplier.add(jMenu5);

        setJMenuBar(jMenuBar_Supplier);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supplier_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_addActionPerformed
        
        SupplierFrame sf=new SupplierFrame();
        sf.setVisible(true);
        dispose();
    }//GEN-LAST:event_supplier_addActionPerformed

    private void supplier_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_viewActionPerformed
        SupplierFrame_view sf_v=new SupplierFrame_view();
        
        Home_Frame hfm=new Home_Frame();
        
        sf_v.setVisible(true);
        dispose();
    }//GEN-LAST:event_supplier_viewActionPerformed

    private void Supplier_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supplier_MenuActionPerformed
        
    }//GEN-LAST:event_Supplier_MenuActionPerformed

    private void jMenuItem_CustomerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CustomerAddActionPerformed
        Customer cs=new Customer();
        cs.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_CustomerAddActionPerformed

    private void jMenuItem_CustomerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CustomerListActionPerformed
            CustomerView csview=new CustomerView();
            csview.setVisible(true);
            dispose();    
    }//GEN-LAST:event_jMenuItem_CustomerListActionPerformed

    private void jMenuItem_StaffAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_StaffAddActionPerformed
        Staff sf=new Staff();
        sf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_StaffAddActionPerformed

    private void jMenuItem_staffLsitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_staffLsitActionPerformed
        StaffView sfview=new StaffView();
        sfview.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_staffLsitActionPerformed

    private void jMenuItem_Transaction_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Transaction_InActionPerformed
        TransactionFrame tf=new TransactionFrame();
        tf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_Transaction_InActionPerformed

    private void jMenuItem_Product_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Product_viewActionPerformed
        ProductFrame_view pf_view=new ProductFrame_view();
        pf_view.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_Product_viewActionPerformed

    private void jMenuItem_Product_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Product_addActionPerformed
        ProductFrame pf=new ProductFrame();
        pf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem_Product_addActionPerformed

    private void jMenu_product_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_product_stockActionPerformed
        StockPageFrame st=new StockPageFrame();
        st.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu_product_stockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Menu_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JMenu Supplier_Menu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    public javax.swing.JMenuBar jMenuBar_Supplier;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem_CustomerAdd;
    private javax.swing.JMenuItem jMenuItem_CustomerList;
    private javax.swing.JMenuItem jMenuItem_Product_add;
    private javax.swing.JMenuItem jMenuItem_Product_view;
    private javax.swing.JMenuItem jMenuItem_StaffAdd;
    private javax.swing.JMenuItem jMenuItem_Transaction_In;
    private javax.swing.JMenuItem jMenuItem_Transaction_out;
    private javax.swing.JMenuItem jMenuItem_staffLsit;
    private javax.swing.JMenu jMenu_product_stock;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem supplier_add;
    private javax.swing.JMenuItem supplier_view;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
