/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ProductFrame_view extends javax.swing.JFrame {

    
    public ProductFrame_view() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         this.setSize(1000, 600);
        this.setLocationRelativeTo(null);

        showProduct();
    }
    
    
    
     public ArrayList<Product> productlist()
     {
        ArrayList<Product> productlist=new ArrayList<>();
        try
        {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=WarehouseManagementSystem;selectMethod=cursor", "sa", "123467");
                Statement statement = connection.createStatement();
                
                ResultSet resultSet=statement.executeQuery("Select product_id,product_name,product_quantity,product_unit,product_price,category from product");
                Product pd;
                
                while(resultSet.next())
                {
                    pd=new Product(resultSet.getInt("product_id"),resultSet.getString("product_name"),resultSet.getString("product_quantity"),resultSet.getString("product_unit"),resultSet.getInt("product_price"),resultSet.getString("category"));           
                    productlist.add(pd);
                }
                
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        return productlist;
    
    }

    public void showProduct()
    {
        ArrayList<Product> pdlist=productlist();
        DefaultTableModel model=(DefaultTableModel)jTable_Product.getModel();
        Object[] row=new Object[6];
        for(int i=0;i<pdlist.size();i++)
        {
            row[0]=pdlist.get(i).getproductID();
            row[1]=pdlist.get(i).getname();
            row[2]=pdlist.get(i).getquantity();
            row[3]=pdlist.get(i).getunit();
            row[4]=pdlist.get(i).getprice();
            row[5]=pdlist.get(i).getcategory();
            //row[7]=pdlist.get(i).getsupplier_id();
            model.addRow(row);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Product = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Proudct_ID = new javax.swing.JTextField();
        txt_Proudct_Name = new javax.swing.JTextField();
        txt_Proudct_Quantity = new javax.swing.JTextField();
        txt_Proudct_Price = new javax.swing.JTextField();
        txt_Category = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Proudct_Unit = new javax.swing.JTextField();
        Button_Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jTable_Product.setBackground(new java.awt.Color(255, 51, 153));
        jTable_Product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Product Quantity", "Product Unit", "Product Price", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Product);

        Delete.setBackground(new java.awt.Color(255, 51, 102));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Back_btn.setBackground(new java.awt.Color(255, 51, 102));
        Back_btn.setText("Back");
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("       Product List          ");

        jLabel2.setText("Product ID");

        jLabel3.setText("Product Name");

        jLabel4.setText("Product Unit ");

        jLabel5.setText("Product Price");

        jLabel6.setText("Category");

        txt_Proudct_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Proudct_NameActionPerformed(evt);
            }
        });

        txt_Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CategoryActionPerformed(evt);
            }
        });

        jLabel8.setText("Product Quantity ");

        txt_Proudct_Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Proudct_UnitActionPerformed(evt);
            }
        });

        Button_Update.setBackground(new java.awt.Color(255, 51, 102));
        Button_Update.setText("Update");
        Button_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Back_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(Button_Update))
                    .addComponent(txt_Proudct_ID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Proudct_Price, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Proudct_Quantity, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Category, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Proudct_Name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Proudct_Unit, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Proudct_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Proudct_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Proudct_Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Proudct_Unit, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Proudct_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Category, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_Update)
                            .addComponent(Delete)
                            .addComponent(Back_btn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=WarehouseManagementSystem;selectMethod=cursor", "sa", "123467");
                Statement statement = connection.createStatement();
                int row = jTable_Product.getSelectedRow();
                String value = (jTable_Product.getModel().getValueAt(row, 0).toString());
                String query = "DELETE from product where product_id=" + value;
                PreparedStatement ps = connection.prepareStatement(query);
                ps.executeUpdate();
                DefaultTableModel model = (DefaultTableModel) jTable_Product.getModel();
                model.setRowCount(0);
                showProduct();
                JOptionPane.showMessageDialog(null, "Deleted Succesfully...");
       }
       catch (Exception e) {
                e.printStackTrace();
            }
       
       txt_Proudct_Name.setText("");
        txt_Proudct_ID.setText("");
        txt_Category.setText("");
        txt_Proudct_Price.setText("");
        txt_Proudct_Unit.setText("");
         txt_Proudct_Quantity.setText("");
    
    }//GEN-LAST:event_DeleteActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        Menu_Frame mf=new Menu_Frame();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_btnActionPerformed

    private void jTable_ProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ProductMouseClicked
        int rowIndex = jTable_Product.getSelectedRow();

        DefaultTableModel model = (DefaultTableModel) jTable_Product.getModel();

        txt_Proudct_ID.setText(model.getValueAt(rowIndex, 0).toString());
        txt_Proudct_Name.setText(model.getValueAt(rowIndex, 1).toString());
        txt_Proudct_Quantity.setText(model.getValueAt(rowIndex, 2).toString());
        txt_Proudct_Unit.setText(model.getValueAt(rowIndex, 3).toString());
        txt_Proudct_Price.setText(model.getValueAt(rowIndex, 4).toString());
        txt_Category.setText(model.getValueAt(rowIndex, 5).toString());
        
        
    }//GEN-LAST:event_jTable_ProductMouseClicked

    private void Button_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_UpdateActionPerformed
       try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=WarehouseManagementSystem;selectMethod=cursor", "sa", "123467");
            Statement statement = connection.createStatement();
             
            int row = jTable_Product.getSelectedRow();
            String value = (jTable_Product.getModel().getValueAt(row, 0).toString());

            String query = "Update product set product_name=?,product_quantity=?,product_unit=?,product_price=?,category=? where product_id="+ value;

            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, txt_Proudct_Name.getText());
            pst.setString(2, txt_Proudct_Quantity.getText());
            pst.setString(3, txt_Proudct_Unit.getText());
            pst.setString(4, txt_Proudct_Price.getText());
            pst.setString(5, txt_Category.getText());

            pst.executeUpdate();

            DefaultTableModel model = (DefaultTableModel) jTable_Product.getModel();
            model.setRowCount(0);
            showProduct();
            JOptionPane.showMessageDialog(null, "Updated Succesfully...");

        } catch (Exception e) {
            e.printStackTrace();
        }
       
       txt_Proudct_Name.setText("");
        txt_Proudct_ID.setText("");
        txt_Category.setText("");
        txt_Proudct_Price.setText("");
        txt_Proudct_Unit.setText("");
         txt_Proudct_Quantity.setText("");
    
    }//GEN-LAST:event_Button_UpdateActionPerformed

    private void txt_Proudct_UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Proudct_UnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Proudct_UnitActionPerformed

    private void txt_CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CategoryActionPerformed

    private void txt_Proudct_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Proudct_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Proudct_NameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductFrame_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductFrame_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductFrame_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductFrame_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductFrame_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JButton Button_Update;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Product;
    private javax.swing.JTextField txt_Category;
    private javax.swing.JTextField txt_Proudct_ID;
    private javax.swing.JTextField txt_Proudct_Name;
    private javax.swing.JTextField txt_Proudct_Price;
    private javax.swing.JTextField txt_Proudct_Quantity;
    private javax.swing.JTextField txt_Proudct_Unit;
    // End of variables declaration//GEN-END:variables
}
